apiVersion: v2
name: agents-oauth
description: A simple CAP project.
type: application
version: 1.0.0
appVersion: 1.0.0
annotations:
  app.kubernetes.io/managed-by: cds-dk/helm
dependencies:
  - name: web-application
    alias: srv
    version: ">0.0.0"
  - name: web-application
    alias: approuter
    version: ">0.0.0"
  - name: service-instance
    alias: destination
    version: ">0.0.0"
  - name: service-instance
    alias: identity
    version: ">0.0.0"
  - name: web-application
    alias: mastra
    version: ">0.0.0"
  - name: service-instance
    alias: postgres
    version: ">0.0.0"
  # - name: web-application
  #   alias: postgresql
  #   version: ">0.0.0"