{{- if .Values.libsql.additionalVolumes }}
{{- range $volume := .Values.libsql.additionalVolumes }}
{{- if $volume.persistentVolumeClaim }}
---
# libsql pvc and secret
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.persistentVolumeClaim.claimName }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "web-application.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: libsql-keys
  labels:
    app.kubernetes.io/name: libsql
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    component: libsql
type: Opaque
data:
  libsql.pub: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxN3AyZlYzY2hpK3JFTnl1cGlRdwpwUXFySEJjNUFLZURoTVB2MnFlWjJhSGRWZS9tMkRJeUJyNllucEFRd0xrRGErMjBFUHozeHVpbUM4TGNpbzlyCjNJczVCQTNCUVBkOTFRdHdFMFRqMFYyV2RmWU9sYy9QRTV6SjhnU3ppZmpoZmQyVkY1UHBnd0tuNTJrSElldjIKcnFPdVRwTXZScmZnZThBd2pCYkRxcFBoaDlpekJ4cHhwWmF6TEhGdDhqUy9ObWQzYUVmekFvWXZpc3FDTjhydgpyUWE2dGFDejZtMEhIei9xdzhlRkNrV1FMMUU4bTdFYVVFWk02bFd3WWFCR2hQQ1RET09URW9vdEFCUlo0dy8wCmdFYlVLc0xBb2dXQWVHWGRwTERxZkxmYnQzY2ovL24zLytHTVpDb2IyMVBmMmJ1eGptZkVZOFo5VGcvNzMrZHUKMXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

{{- end }}
{{- end }}
{{- end }}
