{{- if .Values.mastra.additionalVolumes }}
{{- range $volume := .Values.mastra.additionalVolumes }}
{{- if $volume.persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.persistentVolumeClaim.claimName }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "web-application.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- end }}
{{- end }}
{{- end }}
