name: Kyma
on:
  workflow_call: 
  workflow_dispatch:
    inputs: 
      containers:
        description: 'If true, build and push container images'
        type: boolean
        required: false
        default: true
      helm:
        description: 'If true, deploy or upgrade helm chart'
        type: boolean
        required: false
        default: true
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

concurrency:
  group: kyma-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_NAME: v1
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: sapmachine:ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: ./.github/actions/kyma-setup
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          user: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          kube-config: ${{ secrets.KUBE_CONFIG }}
          
      - run: npm install --omit=optional
      - run: ./.github/actions/version/set-release-version.sh
        
      - run: release=$(jq -r '.name' package.json) >> $GITHUB_ENV
      - run: echo "Release version set to $release"
        
      - run: npm run build:containers -- --push 
        if: inputs.containers == true
        
      # if we did not build containers, we need to build the cds project for helm deployment
      - run: npx cds build --production
        if: inputs.containers == false

      - run: helm upgrade $release ./gen/chart --install --create-namespace --set global.image.tag=$release
        if: inputs.helm == true

      - uses: ./.github/actions/kyma-info
        if: always()
        with:
          app: ${{ env.APP_NAME }}
