name: Kyma
on:
  workflow_call: 
  workflow_dispatch:
    inputs: 
      containers:
        description: 'If true, build and push container images'
        type: boolean
        required: false
        default: true
      helm:
        description: 'If true, deploy or upgrade helm chart'
        type: boolean
        required: false
        default: true
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

concurrency:
  group: kyma-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_NAME: v1
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: sapmachine:ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "pnpm"


      - name: pnpm approve-builds
        run: pnpm approve-builds esbuild, onnxruntime-node, protobufjs
        
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

  
      - uses: ./.github/actions/kyma-setup
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          user: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          kube-config: ${{ secrets.KUBE_CONFIG }}
          
      
      - name: Set release version
        shell: bash
        run: |
          # Get current git reference (branch, tag, or commit)
          if [ -n "$GITHUB_REF" ]; then
              REF="$GITHUB_REF"
          else
              REF="refs/heads/$(git rev-parse --abbrev-ref HEAD)"
          fi
          
          echo "Git reference: $REF"
          
          # Determine version based on ref type
          if [[ "$REF" == refs/tags/* ]]; then
              VERSION=$(echo "$REF" | sed 's|refs/tags/||' | sed 's/\./-/g')
              echo "Tag detected: $VERSION"
          elif [[ "$REF" == refs/heads/release/* ]]; then
              VERSION=$(echo "$REF" | sed 's|refs/heads/release/||' | sed 's/\./-/g')
              echo "Release branch detected: $VERSION"
          elif [[ "$REF" == refs/heads/feature/* ]]; then
              VERSION=$(echo "$REF" | sed 's|refs/heads/feature/||' | sed 's/\./-/g')
              echo "Feature branch detected: $VERSION"
          elif [[ "$REF" == refs/heads/main ]] || [[ "$REF" == refs/heads/master ]]; then
              VERSION="main"
              echo "Main branch detected: $VERSION"
          else
              VERSION=$(echo "$REF" | sed 's|refs/heads/||' | sed 's|/|-|g' | sed 's/\./-/g')
              echo "Other ref detected: $VERSION"
          fi
          
          # Sanitize version name for Kubernetes
          VERSION=$(echo "$VERSION" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
          
          # Ensure version doesn't exceed Kubernetes name limits (63 characters)
          if [ ${#VERSION} -gt 63 ]; then
              VERSION="${VERSION:0:63}"
              VERSION=$(echo "$VERSION" | sed 's/-$//g')
          fi
          
          echo "Final sanitized version: $VERSION"
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Release version set to: $VERSION"
        
      - run: pnpm build:containers -- --push 
        if: inputs.containers == true
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        
      # if we did not build containers, we need to build the cds project for helm deployment
      - run: pnpm build
        if: inputs.containers == false

      - run: helm upgrade $RELEASE_VERSION ./gen/chart --install --namespace devspace --set global.image.tag=$RELEASE_VERSION
        if: inputs.helm == true
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - uses: ./.github/actions/kyma-info
        if: always()
        with:
          app: ${{ env.APP_NAME }}
